-- db/local/schema.sql — dev-only schema design scratchpad.
-- NOT the source of truth (that's the external migrations repo).
-- DROP-and-CREATE: running this destroys all local data.
--
-- Implements db/local/spec/schema-spec-users.md (users, auth, roles, permissions, audit).
-- Tables are created in the spec's dependency order — the file runs top to
-- bottom with no forward references. Seed data lives in seed.sql.

DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

------------------------------------------------------------------------------
-- Tenancy: client, role
------------------------------------------------------------------------------

CREATE TABLE client (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name varchar(64) NOT NULL UNIQUE
);

COMMENT ON COLUMN client.id IS 'Unique identifier for each client';
COMMENT ON COLUMN client.name IS 'Name of the client';

CREATE TABLE role (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  -- Nullable deliberately (db/local/spec/schema-spec-users.md open item 1): a NULL may come to mean a
  -- global role; undecided.
  client_id int REFERENCES client (id)
);

CREATE INDEX idx_role_client_id ON role (client_id);

COMMENT ON COLUMN role.id IS 'Unique identifier for each role';
COMMENT ON COLUMN role.name IS 'Name of the role (clients may choose their own names)';
COMMENT ON COLUMN role.client_id IS 'The client this role belongs to. Nullable — see open items';

------------------------------------------------------------------------------
-- better-auth tables: "user", session, account, verification
--
-- ⚠ Generated by better-auth — config is the source of truth. Present here
-- only so codegen has types. Do not hand-edit to add columns — except the
-- "user" add-ons (phone_number, client_id, role_id), which are deliberate
-- extensions to better-auth's default user model.
--
-- "user" is a PostgreSQL reserved word and is double-quoted everywhere.
------------------------------------------------------------------------------

CREATE TABLE "user" (
  id text NOT NULL PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  email_verified boolean NOT NULL,
  image text,
  phone_number text,
  client_id int NOT NULL REFERENCES client (id),
  role_id int NOT NULL REFERENCES role (id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL
);

CREATE INDEX idx_user_client_id ON "user" (client_id);
CREATE INDEX idx_user_role_id ON "user" (role_id);

COMMENT ON COLUMN "user".id IS 'Unique identifier for each user';
COMMENT ON COLUMN "user".name IS 'User''s chosen display name';
COMMENT ON COLUMN "user".email IS 'User''s email address for communication and login';
COMMENT ON COLUMN "user".email_verified IS 'Whether the user''s email is verified';
COMMENT ON COLUMN "user".image IS 'User''s image url';
COMMENT ON COLUMN "user".phone_number IS 'User''s phone number';
COMMENT ON COLUMN "user".client_id IS 'The client this user belongs to';
COMMENT ON COLUMN "user".role_id IS 'The user''s single role';
COMMENT ON COLUMN "user".created_at IS 'When the user account was created';
COMMENT ON COLUMN "user".updated_at IS 'Last update to the user''s information';

CREATE TABLE session (
  id text NOT NULL PRIMARY KEY,
  user_id text NOT NULL REFERENCES "user" (id),
  token text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  ip_address text,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL
);

-- Session lookup by token is covered by the UNIQUE constraint's index.
CREATE INDEX idx_session_user_id ON session (user_id);

COMMENT ON COLUMN session.id IS 'Unique identifier for each session';
COMMENT ON COLUMN session.user_id IS 'The ID of the user';
COMMENT ON COLUMN session.token IS 'The unique session token';
COMMENT ON COLUMN session.expires_at IS 'When the session expires';
COMMENT ON COLUMN session.ip_address IS 'The IP address of the device';
COMMENT ON COLUMN session.user_agent IS 'The user agent information of the device';
COMMENT ON COLUMN session.created_at IS 'When the session was created';
COMMENT ON COLUMN session.updated_at IS 'When the session was updated';

CREATE TABLE account (
  id text NOT NULL PRIMARY KEY,
  user_id text NOT NULL REFERENCES "user" (id),
  account_id text NOT NULL,
  provider_id text NOT NULL,
  access_token text,
  refresh_token text,
  access_token_expires_at timestamptz,
  refresh_token_expires_at timestamptz,
  scope text,
  id_token text,
  password text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL
);

CREATE INDEX idx_account_user_id ON account (user_id);

COMMENT ON COLUMN account.id IS 'Unique identifier for each account';
COMMENT ON COLUMN account.user_id IS 'The ID of the user';
COMMENT ON COLUMN account.account_id IS 'The ID of the account as provided by the SSO, or equal to user_id for credential accounts';
COMMENT ON COLUMN account.provider_id IS 'The ID of the provider';
COMMENT ON COLUMN account.access_token IS 'The access token of the account. Returned by the provider';
COMMENT ON COLUMN account.refresh_token IS 'The refresh token of the account. Returned by the provider';
COMMENT ON COLUMN account.access_token_expires_at IS 'When the access token expires';
COMMENT ON COLUMN account.refresh_token_expires_at IS 'When the refresh token expires';
COMMENT ON COLUMN account.scope IS 'The scope of the account. Returned by the provider';
COMMENT ON COLUMN account.id_token IS 'The ID token returned from the provider';
COMMENT ON COLUMN account.password IS 'The password of the account. Mainly used for email and password authentication';
COMMENT ON COLUMN account.created_at IS 'When the account was created';
COMMENT ON COLUMN account.updated_at IS 'When the account was updated';

CREATE TABLE verification (
  id text NOT NULL PRIMARY KEY,
  identifier text NOT NULL,
  value text NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL
);

CREATE INDEX idx_verification_identifier ON verification (identifier);

COMMENT ON COLUMN verification.id IS 'Unique identifier for each verification';
COMMENT ON COLUMN verification.identifier IS 'The identifier for the verification request';
COMMENT ON COLUMN verification.value IS 'The value to be verified';
COMMENT ON COLUMN verification.expires_at IS 'When the verification request expires';
COMMENT ON COLUMN verification.created_at IS 'When the verification request was created';
COMMENT ON COLUMN verification.updated_at IS 'When the verification request was updated';

------------------------------------------------------------------------------
-- Preferences
------------------------------------------------------------------------------

CREATE TABLE preference (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL UNIQUE REFERENCES "user" (id),
  -- map_style and theme stay text for now; possible future Postgres enums.
  -- Validate allowed values at the API boundary with TypeBox in the meantime.
  map_style text,
  layers_on_load jsonb,
  favorite jsonb,
  theme text,
  data_vis_preset jsonb
);

COMMENT ON COLUMN preference.id IS 'Unique identifier for each preference row';
COMMENT ON COLUMN preference.user_id IS 'The ID of the user. One preference row per user';
COMMENT ON COLUMN preference.map_style IS 'The style of map the user chooses to display on render';
COMMENT ON COLUMN preference.layers_on_load IS 'The layers the user wants to see on the map on load';
COMMENT ON COLUMN preference.favorite IS '(mobile) The favorites the user wants at the top of the bottom drawer menu';
COMMENT ON COLUMN preference.theme IS 'The theme of the app the user wants on load';
COMMENT ON COLUMN preference.data_vis_preset IS 'User presets for data visualizer graph';

------------------------------------------------------------------------------
-- Permissions
------------------------------------------------------------------------------

CREATE TABLE permission (
  -- BY DEFAULT (not ALWAYS): seed data specifies explicit ids.
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  description text NOT NULL,
  assign_role boolean NOT NULL
);

COMMENT ON COLUMN permission.id IS 'Unique identifier for a permission';
COMMENT ON COLUMN permission.name IS 'Name of the permission';
COMMENT ON COLUMN permission.description IS 'Description of what the permission does';
COMMENT ON COLUMN permission.assign_role IS 'Whether this permission may be attached to a role. false means it can only be granted to an individual user';

CREATE TABLE role_permission (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  role_id int NOT NULL REFERENCES role (id),
  permission_id int NOT NULL REFERENCES permission (id),
  UNIQUE (role_id, permission_id)
);

CREATE INDEX idx_role_permission_role_id ON role_permission (role_id);
CREATE INDEX idx_role_permission_permission_id ON role_permission (permission_id);

CREATE TABLE granted_permission (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  permission_id int NOT NULL REFERENCES permission (id),
  user_id text NOT NULL REFERENCES "user" (id),
  UNIQUE (user_id, permission_id)
);

CREATE INDEX idx_granted_permission_user_id ON granted_permission (user_id);
CREATE INDEX idx_granted_permission_permission_id ON granted_permission (permission_id);

COMMENT ON TABLE granted_permission IS 'Permissions granted to an individual user, outside their role';

------------------------------------------------------------------------------
-- Invitations
--
-- Flow: a client manager creates an invite, picking the role the new user
-- will receive → the invitee receives an email containing
-- https://<app>/invite?token=<token> → clicking it opens the signup page.
-- The invite carries the role, so signup assigns it directly.
------------------------------------------------------------------------------

CREATE TABLE invite (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  token uuid NOT NULL UNIQUE,
  expires_at timestamptz,
  sender_user_id text NOT NULL REFERENCES "user" (id),
  client_id int NOT NULL REFERENCES client (id),
  role_id int NOT NULL REFERENCES role (id)
);

-- token is already unique (index comes with the constraint).
CREATE INDEX idx_invite_sender_user_id ON invite (sender_user_id);
CREATE INDEX idx_invite_client_id ON invite (client_id);
CREATE INDEX idx_invite_role_id ON invite (role_id);

COMMENT ON COLUMN invite.id IS 'Unique identifier for invites';
COMMENT ON COLUMN invite.token IS 'uuid for the invite token url';
COMMENT ON COLUMN invite.expires_at IS 'When the invite token expires';
COMMENT ON COLUMN invite.sender_user_id IS 'The user who sent the invite';
COMMENT ON COLUMN invite.client_id IS 'The client the invitee will belong to';
COMMENT ON COLUMN invite.role_id IS 'The role the invited user will receive on signup';

-- Kept as a separate table for now.
CREATE TABLE accepted_invites (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  invite_id int NOT NULL REFERENCES invite (id),
  accepted_date timestamptz NOT NULL DEFAULT now(),
  user_id text NOT NULL REFERENCES "user" (id),
  UNIQUE (invite_id)
);

CREATE INDEX idx_accepted_invites_user_id ON accepted_invites (user_id);

COMMENT ON COLUMN accepted_invites.id IS 'Unique identifier for the acceptance record';
COMMENT ON COLUMN accepted_invites.invite_id IS 'The invite that was accepted';
COMMENT ON COLUMN accepted_invites.accepted_date IS 'When the invite was accepted';
COMMENT ON COLUMN accepted_invites.user_id IS 'The user created by accepting the invite';

------------------------------------------------------------------------------
-- Devices
--
-- ⚠ PLACEHOLDER — to be reconciled with the real device table in the main
-- ATLASRain schema. Exists only so control_audit_log.device_id has a valid
-- foreign key target in this local scratchpad. Do not add columns to it or
-- build against it.
------------------------------------------------------------------------------

CREATE TABLE device (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY
);

COMMENT ON TABLE device IS 'PLACEHOLDER — reconcile with the real device table in the main ATLASRain schema';
COMMENT ON COLUMN device.id IS 'Placeholder device identifier';

------------------------------------------------------------------------------
-- Audit logging
------------------------------------------------------------------------------

CREATE TABLE audit_log_action (
  -- BY DEFAULT (not ALWAYS): seed data specifies explicit ids.
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- 32 chars (raised from 16): UPDATE_DEVICE_CONFIG is 20.
  action_id varchar(32) NOT NULL UNIQUE,
  -- 64 chars (raised from 32): two seed labels are 35 and 39 chars.
  action_text varchar(64) NOT NULL
);

COMMENT ON TABLE audit_log_action IS 'The type of action a user performed on the system';
COMMENT ON COLUMN audit_log_action.action_id IS 'Stable machine key';
COMMENT ON COLUMN audit_log_action.action_text IS 'Human-readable label';

CREATE TABLE control_audit_log (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  date timestamptz NOT NULL DEFAULT now(),
  log_action_id int NOT NULL REFERENCES audit_log_action (id),
  device_id int NOT NULL REFERENCES device (id),
  actor_id text NOT NULL REFERENCES "user" (id)
);

CREATE INDEX idx_control_audit_log_date ON control_audit_log (date);
CREATE INDEX idx_control_audit_log_device_id ON control_audit_log (device_id);
CREATE INDEX idx_control_audit_log_actor_id ON control_audit_log (actor_id);

COMMENT ON TABLE control_audit_log IS 'Device control actions';
COMMENT ON COLUMN control_audit_log.date IS 'When the action occurred';
COMMENT ON COLUMN control_audit_log.log_action_id IS 'What action was performed';
COMMENT ON COLUMN control_audit_log.device_id IS 'The device acted upon';
COMMENT ON COLUMN control_audit_log.actor_id IS 'The user who performed the action';

CREATE TABLE user_audit_log (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  date timestamptz NOT NULL DEFAULT now(),
  log_action_id int NOT NULL REFERENCES audit_log_action (id),
  actor_id text NOT NULL REFERENCES "user" (id),
  target_id text NOT NULL REFERENCES "user" (id)
);

CREATE INDEX idx_user_audit_log_date ON user_audit_log (date);
CREATE INDEX idx_user_audit_log_actor_id ON user_audit_log (actor_id);
CREATE INDEX idx_user_audit_log_target_id ON user_audit_log (target_id);

COMMENT ON TABLE user_audit_log IS 'User management actions';
COMMENT ON COLUMN user_audit_log.date IS 'When the action occurred';
COMMENT ON COLUMN user_audit_log.log_action_id IS 'What action was performed';
COMMENT ON COLUMN user_audit_log.actor_id IS 'The user who performed the action';
COMMENT ON COLUMN user_audit_log.target_id IS 'The user the action was performed on';

CREATE TABLE roles_perms_audit_log (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  date timestamptz NOT NULL DEFAULT now(),
  log_action_id int NOT NULL REFERENCES audit_log_action (id),
  actor_id text NOT NULL REFERENCES "user" (id),
  -- role_id, permission_id, and added are nullable because not every action
  -- involves all three — CREATE_ROLE and DELETE_ROLE have a role but no
  -- permission.
  role_id int REFERENCES role (id),
  permission_id int REFERENCES permission (id),
  added boolean
);

CREATE INDEX idx_roles_perms_audit_log_date ON roles_perms_audit_log (date);
CREATE INDEX idx_roles_perms_audit_log_actor_id ON roles_perms_audit_log (actor_id);
CREATE INDEX idx_roles_perms_audit_log_role_id ON roles_perms_audit_log (role_id);

COMMENT ON TABLE roles_perms_audit_log IS 'Role and permission changes';
COMMENT ON COLUMN roles_perms_audit_log.date IS 'When the action occurred';
COMMENT ON COLUMN roles_perms_audit_log.log_action_id IS 'What action was performed';
COMMENT ON COLUMN roles_perms_audit_log.actor_id IS 'The user who performed the action';
COMMENT ON COLUMN roles_perms_audit_log.role_id IS 'The role affected';
COMMENT ON COLUMN roles_perms_audit_log.permission_id IS 'The permission affected';
COMMENT ON COLUMN roles_perms_audit_log.added IS 'TRUE if the permission was added, FALSE if removed';

------------------------------------------------------------------------------
-- Voting — not designed. No voting tables are defined here on purpose
-- (db/local/spec/schema-spec-users.md: "Do not invent them"). Permissions RW_CLIENT_VOTES (23) and
-- EX_CLIENT_VOTES (24) exist in the seed data for this future work.
------------------------------------------------------------------------------
