-- db/local/seed.sql — local seed data, applied by `bun run db:seed`.
-- Implements the seed tables in db/local/spec/schema-spec-users.md. Assumes a fresh database
-- (db:reset just ran): client and role use GENERATED ALWAYS identities, so
-- their ids come from insert order — do not reorder these inserts.

------------------------------------------------------------------------------
-- client (ids 1..2 by insert order)
------------------------------------------------------------------------------

INSERT INTO client (name) VALUES
  ('Torres & Associates'), -- id 1
  ('City of Bryan');       -- id 2

------------------------------------------------------------------------------
-- role (ids 1..4 by insert order)
------------------------------------------------------------------------------

INSERT INTO role (name, client_id) VALUES
  ('ADMIN', 1),          -- id 1
  ('TECHNICIAN', 1),     -- id 2
  ('CLIENT_MANAGER', 2), -- id 3
  ('TECHNICIAN', 2);     -- id 4

------------------------------------------------------------------------------
-- permission (explicit ids; identity is GENERATED BY DEFAULT)
------------------------------------------------------------------------------

-- Read (R_) and write (W_) are separate permissions: W_ does not imply R_.
-- Roles that need both hold both.
INSERT INTO permission (id, name, description, assign_role) VALUES
  (1, 'R_CLIENT_DEVICES', 'Can read all flood-warning related devices for their client', TRUE),
  (2, 'W_CLIENT_DEVICES', 'Can write all flood-warning related devices for their client', TRUE),
  (3, 'R_EXTERNAL_DEVICES', 'Can read all flood-warning related devices for all clients', TRUE),
  (4, 'W_EXTERNAL_DEVICES', 'Can write all flood-warning related devices across all clients', TRUE),
  (5, 'R_CLIENT_CONTROL_PANEL', 'Can read all manual overrides on the control panel for their client', TRUE),
  (6, 'W_CLIENT_CONTROL_PANEL', 'Can write manual overrides on the control panel for their client', TRUE),
  (7, 'R_EXTERNAL_CONTROL_PANEL', 'Can read all manual overrides on the control panel for all clients', TRUE),
  (8, 'W_EXTERNAL_CONTROL_PANEL', 'Can write manual overrides on the control panel for all clients', TRUE),
  (9, 'R_CLIENT_USERS', 'Can read all users in their client', TRUE),
  (10, 'W_CLIENT_USERS', 'Can write all users in their client', TRUE),
  (11, 'R_EXTERNAL_USERS', 'Can read all users across all clients', TRUE),
  (12, 'W_EXTERNAL_USERS', 'Can write all users across all clients', TRUE),
  (13, 'R_CLIENTS', 'Can read all clients', TRUE),
  (14, 'W_CLIENTS', 'Can write all clients', TRUE),
  (15, 'EX_CLIENT_ALERT', 'Can send alerts to all manual alert subscribers within his client', TRUE),
  (16, 'EX_EXTERNAL_ALERT', 'Can send alert to all manual alert subscribers across all clients', TRUE),
  (17, 'EX_EMAIL_SUB', 'Can subscribe for email based alerts', TRUE),
  (18, 'EX_TEXT_SUB', 'Can subscribe for text/SMS-based alerts', TRUE),
  (19, 'R_CLIENT_REPORTS', 'Can read all reports for their client', TRUE),
  (20, 'W_CLIENT_REPORTS', 'Can write all reports for their client', TRUE),
  (21, 'R_EXTERNAL_REPORTS', 'Can read all reports for all clients', TRUE),
  (22, 'W_EXTERNAL_REPORTS', 'Can write all reports for all clients', TRUE),
  (23, 'R_CLIENT_LIFT_STATIONS', 'Can read all lift station devices for their client', TRUE),
  (24, 'W_CLIENT_LIFT_STATIONS', 'Can write all lift station devices for their client', TRUE),
  (25, 'R_EXTERNAL_LIFT_STATIONS', 'Can read all lift station devices for all clients', TRUE),
  (26, 'W_EXTERNAL_LIFT_STATIONS', 'Can write all lift station devices for all clients', TRUE),
  (27, 'R_CLIENT_VOTES', 'Can read all votes to all people in their client', TRUE),
  (28, 'W_CLIENT_VOTES', 'Can assign votes to all people in their client', TRUE),
  (29, 'EX_CLIENT_VOTES', 'Can execute and vote on votes for their client', FALSE);

-- Explicit-id inserts don't advance the identity sequence; move it past the
-- highest seeded id so future inserts don't collide.
SELECT setval(pg_get_serial_sequence('permission', 'id'), (SELECT max(id) FROM permission));

------------------------------------------------------------------------------
-- role_permission (hand-written assignments; role ids per insert order above)
------------------------------------------------------------------------------

-- W_ does not imply read, so a role that can write a resource also holds the
-- R_ counterpart (where one exists). Permission 29 (EX_CLIENT_VOTES) is
-- deliberately not attached to any role because assign_role = FALSE.

-- ADMIN (Torres & Associates, role 1)
INSERT INTO role_permission (role_id, permission_id) VALUES
  (1, 3), (1, 4), (1, 7), (1, 8), (1, 11), (1, 12), (1, 13), (1, 14), (1, 16),
  (1, 17), (1, 18), (1, 21), (1, 22), (1, 25), (1, 26);

-- TECHNICIAN (Torres & Associates, role 2)
INSERT INTO role_permission (role_id, permission_id) VALUES
  (2, 3), (2, 4), (2, 7), (2, 8), (2, 11), (2, 17), (2, 18), (2, 21), (2, 22),
  (2, 25), (2, 26);

-- CLIENT_MANAGER (City of Bryan, role 3)
INSERT INTO role_permission (role_id, permission_id) VALUES
  (3, 1), (3, 2), (3, 5), (3, 6), (3, 9), (3, 10), (3, 15), (3, 17), (3, 18),
  (3, 19), (3, 20), (3, 23), (3, 24), (3, 27), (3, 28);

-- TECHNICIAN (City of Bryan, role 4)
INSERT INTO role_permission (role_id, permission_id) VALUES
  (4, 1), (4, 2), (4, 5), (4, 6), (4, 15), (4, 17), (4, 18), (4, 19), (4, 20);
------------------------------------------------------------------------------
-- audit_log_action (explicit ids; identity is GENERATED BY DEFAULT)
-- "Intialization" (id 14) is a typo in the source, preserved verbatim.
------------------------------------------------------------------------------

INSERT INTO audit_log_action (id, action_id, action_text) VALUES
  (1, 'WIFI_ON', 'Wifi On'),
  (2, 'WIFI_OFF', 'Wifi Off'),
  (3, 'MAN_OVERTOP_ON', 'Triggered Manual Overtop'),
  (4, 'MAN_OVERTOP_OFF', 'Untriggered Manual Overtop'),
  (5, 'PING', 'Pinged Device'),
  (6, 'MAN_MEASURE', 'Manual Measurement'),
  (7, 'MAN_FLASHER_ON', 'Manual Activation of Flasher'),
  (8, 'MAN_FLASHER_OFF', 'Manual Deactivation of Flasher'),
  (9, 'REQ_IMAGE', 'Manual Request of Image'),
  (10, 'REQ_VIDEO', 'Manual Request of Video'),
  (11, 'SET_CAMERA_PRESET', 'Manual setting of the Camera Preset'),
  (12, 'BARRIER_ARM_OPEN', 'Manual Opening Barrier Arm'),
  (13, 'BARRIER_ARM_CLOSED', 'Manual Closing of Barrier Arm'),
  (14, 'INIT_DEVICE', 'Intialization of a New Device'),
  (15, 'REGISTER_DEVICE', 'Registering a New Device'),
  (16, 'UPDATE_DEVICE_CONFIG', 'Updating/Editing Device''s Config'),
  (17, 'INVITE_USER', 'Inviting a new user'),
  (18, 'DELETE_INVITE_USER', 'Deleting an invite for a new User'),
  (19, 'DELETE_USER', 'Deleting a User'),
  (20, 'UPDATE_USER', 'Updating/Editing a User''s Config'),
  (21, 'CREATE_ROLE', 'Create a new role'),
  (22, 'UPDATE_ROLE_PERMISSIONS', 'Updating the permissions tied to a role'),
  (23, 'DELETE_ROLE', 'Deleting a role');

SELECT setval(pg_get_serial_sequence('audit_log_action', 'id'), (SELECT max(id) FROM audit_log_action));
