-- db/local/seed.sql — local seed data, applied by `bun run db:seed`.
-- Implements the seed tables in db/local/spec/schema-spec-users.md. Assumes a fresh database
-- (db:reset just ran): client and role use GENERATED ALWAYS identities, so
-- their ids come from insert order — do not reorder these inserts.

------------------------------------------------------------------------------
-- client (ids 1..2 by insert order)
------------------------------------------------------------------------------

INSERT INTO client (name) VALUES
  ('Torres & Associates'), -- id 1
  ('City of Bryan');       -- id 2

------------------------------------------------------------------------------
-- role (ids 1..4 by insert order)
------------------------------------------------------------------------------

INSERT INTO role (name, client_id) VALUES
  ('ADMIN', 1),          -- id 1
  ('TECHNICIAN', 1),     -- id 2
  ('CLIENT_MANAGER', 2), -- id 3
  ('TECHNICIAN', 2);     -- id 4

------------------------------------------------------------------------------
-- permission (explicit ids; identity is GENERATED BY DEFAULT)
------------------------------------------------------------------------------

-- Read (R_) and write (W_) are separate permissions: W_ does not imply R_.
-- Roles that need both hold both.
INSERT INTO permission (id, name, description, assign_role) VALUES
  (1, 'R_CLIENT_DEVICES', 'Can read all flood-warning related devices for their client', TRUE),
  (2, 'W_CLIENT_DEVICES', 'Can write all flood-warning related devices for their client', TRUE),
  (3, 'R_EXTERNAL_DEVICES', 'Can read all flood-warning related devices for all clients', TRUE),
  (4, 'W_EXTERNAL_DEVICES', 'Can write all flood-warning related devices across all clients', TRUE),
  (5, 'W_CLIENT_CONTROL_PANEL', 'Can write manual overrides on the control panel for their client', TRUE),
  (6, 'W_EXTERNAL_CONTROL_PANEL', 'Can write manual overrides on the control panel for all clients', TRUE),
  (7, 'R_CLIENT_USERS', 'Can read all users in their client', TRUE),
  (8, 'W_CLIENT_USERS', 'Can write all users in their client', TRUE),
  (9, 'R_EXTERNAL_USERS', 'Can read all users across all clients', TRUE),
  (10, 'W_EXTERNAL_USERS', 'Can write all users across all clients', TRUE),
  (11, 'R_CLIENTS', 'Can read all clients', TRUE),
  (12, 'W_CLIENTS', 'Can write all clients', TRUE),
  (13, 'EX_CLIENT_ALERT', 'Can send alerts to all manual alert subscribers within his client', TRUE),
  (14, 'EX_EXTERNAL_ALERT', 'Can send alert to all manual alert subscribers across all clients', TRUE),
  (15, 'EX_EMAIL_SUB', 'Can subscribe for email based alerts', TRUE),
  (16, 'EX_TEXT_SUB', 'Can subscribe for text/SMS-based alerts', TRUE),
  (17, 'R_CLIENT_REPORTS', 'Can read all reports for their client', TRUE),
  (18, 'W_CLIENT_REPORTS', 'Can write all reports for their client', TRUE),
  (19, 'R_EXTERNAL_REPORTS', 'Can read all reports for all clients', TRUE),
  (20, 'W_EXTERNAL_REPORTS', 'Can write all reports for all clients', TRUE),
  (21, 'W_CLIENT_LIFT_STATIONS', 'Can write all lift station devices for their client', TRUE),
  (22, 'W_EXTERNAL_LIFT_STATIONS', 'Can write all lift station devices for all clients', TRUE),
  (23, 'W_CLIENT_VOTES', 'Can assign votes to all people in their client', TRUE),
  (24, 'EX_CLIENT_VOTES', 'Can execute and vote on votes for their client', FALSE);

-- Explicit-id inserts don't advance the identity sequence; move it past the
-- highest seeded id so future inserts don't collide.
SELECT setval(pg_get_serial_sequence('permission', 'id'), (SELECT max(id) FROM permission));

------------------------------------------------------------------------------
-- role_permission (hand-written assignments; role ids per insert order above)
------------------------------------------------------------------------------

-- W_ does not imply read, so a role that can write a resource also holds the
-- R_ counterpart (where one exists).

-- ADMIN (Torres & Associates, role 1)
INSERT INTO role_permission (role_id, permission_id) VALUES
  (1, 3), (1, 4), (1, 6), (1, 9), (1, 10), (1, 11), (1, 12), (1, 14), (1, 15),
  (1, 16), (1, 19), (1, 20), (1, 22);

-- TECHNICIAN (Torres & Associates, role 2)
INSERT INTO role_permission (role_id, permission_id) VALUES
  (2, 3), (2, 4), (2, 6), (2, 9), (2, 11), (2, 15), (2, 16), (2, 19), (2, 20),
  (2, 22);

-- CLIENT_MANAGER (City of Bryan, role 3)
INSERT INTO role_permission (role_id, permission_id) VALUES
  (3, 1), (3, 2), (3, 5), (3, 7), (3, 8), (3, 13), (3, 15), (3, 16), (3, 17),
  (3, 18), (3, 23);

-- TECHNICIAN (City of Bryan, role 4)
INSERT INTO role_permission (role_id, permission_id) VALUES
  (4, 1), (4, 2), (4, 5), (4, 13), (4, 15), (4, 16), (4, 17), (4, 18);

------------------------------------------------------------------------------
-- audit_log_action (explicit ids; identity is GENERATED BY DEFAULT)
-- "Intialization" (id 14) is a typo in the source, preserved verbatim.
------------------------------------------------------------------------------

INSERT INTO audit_log_action (id, action_id, action_text) VALUES
  (1, 'WIFI_ON', 'Wifi On'),
  (2, 'WIFI_OFF', 'Wifi Off'),
  (3, 'MAN_OVERTOP_ON', 'Triggered Manual Overtop'),
  (4, 'MAN_OVERTOP_OFF', 'Untriggered Manual Overtop'),
  (5, 'PING', 'Pinged Device'),
  (6, 'MAN_MEASURE', 'Manual Measurement'),
  (7, 'MAN_FLASHER_ON', 'Manual Activation of Flasher'),
  (8, 'MAN_FLASHER_OFF', 'Manual Deactivation of Flasher'),
  (9, 'REQ_IMAGE', 'Manual Request of Image'),
  (10, 'REQ_VIDEO', 'Manual Request of Video'),
  (11, 'SET_CAMERA_PRESET', 'Manual setting of the Camera Preset'),
  (12, 'BARRIER_ARM_OPEN', 'Manual Opening Barrier Arm'),
  (13, 'BARRIER_ARM_CLOSED', 'Manual Closing of Barrier Arm'),
  (14, 'INIT_DEVICE', 'Intialization of a New Device'),
  (15, 'REGISTER_DEVICE', 'Registering a New Device'),
  (16, 'UPDATE_DEVICE_CONFIG', 'Updating/Editing Device''s Config'),
  (17, 'DELETE_USER', 'Deleting a User'),
  (18, 'UPDATE_USER', 'Updating/Editing a User''s Config'),
  (19, 'CREATE_ROLE', 'Create a new role'),
  (20, 'UPDATE_ROLE_PERMISSIONS', 'Updating the permissions tied to a role'),
  (21, 'DELETE_ROLE', 'Deleting a role');

SELECT setval(pg_get_serial_sequence('audit_log_action', 'id'), (SELECT max(id) FROM audit_log_action));
