/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AlertLevel = "device" | "gauge_station";

export type DeviceType = "barrier_arm" | "camera" | "datalogger" | "flasher";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type InternalPowerSensorMeasurementType = "current" | "power" | "voltage";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type NotificationType = "email" | "sms";

export type ProtocolType = "coap" | "mqtt";

export type SeasonalReportQuestionResponse = "no" | "unknown" | "yes";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type WorkOrderState = "cancelled" | "completed" | "in_progress" | "not_started";

export interface AcceptedInvites {
  accepted_date: Timestamp;
  id: Generated<number>;
  invite_id: number;
  user_id: string;
}

export interface Account {
  access_token: string | null;
  access_token_expires_at: Timestamp | null;
  account_id: string;
  created_at: Timestamp;
  id: string;
  id_token: string | null;
  password: string | null;
  provider_id: string;
  refresh_token: string | null;
  refresh_token_expires_at: Timestamp | null;
  scope: string | null;
  updated_at: Timestamp;
  user_id: string;
}

export interface Alert {
  archived: Timestamp | null;
  client_id: number | null;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  level: AlertLevel;
  type: string;
}

export interface AlertInfo {
  alert_id: number;
  archived: Timestamp | null;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  notification_type: NotificationType;
  retract_message: string | null;
  send_message: string | null;
}

export interface AlertMonitor {
  archived: Timestamp | null;
  device_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  local_id: number;
  type_id: number;
}

export interface AlertMonitorChannel {
  alert_monitor_id: number;
  archived: Timestamp | null;
  channel_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
}

export interface AlertMonitorConfig {
  alert_id: number;
  alert_monitor_id: number;
  archived: Timestamp | null;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
}

export interface AlertMonitorConfigActivity {
  active: boolean;
  alert_monitor_id: number;
  archived: Timestamp | null;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
}

export interface AlertMonitorConfigActivityOverride {
  alert_monitor_id: number;
  archived: Timestamp | null;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  override: boolean | null;
}

export interface AlertMonitorConfigEnabled {
  alert_monitor_id: number;
  archived: Timestamp | null;
  enabled: boolean;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
}

export interface AlertMonitorConfigRange {
  alert_monitor_id: number;
  archived: Timestamp | null;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  max_value: number;
  min_value: number;
}

export interface AlertSubscription {
  alert_id: number;
  archived: Timestamp | null;
  gauge_station_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  notification_type: NotificationType;
  user_id: string;
}

export interface Asset {
  asset_type_id: number;
  cost: string | null;
  creation_date: Timestamp;
  deploy_date: Timestamp | null;
  eos_date: Timestamp | null;
  gauge_station_id: number | null;
  id: Generated<number>;
  serial_number: string | null;
}

export interface AssetType {
  current_value: string | null;
  id: Generated<number>;
  is_deprecated: Generated<boolean>;
  lifespan: number | null;
  name: string;
  owner_client_id: number;
  point_of_sale: string | null;
}

export interface AuditLogAction {
  action_id: string;
  action_text: string;
  id: Generated<number>;
}

export interface Camera {
  archived: Timestamp | null;
  device_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  local_id: number;
}

export interface CameraCaptureData {
  camera_data_record_id: Int8;
  file_type: string;
  id: Generated<number>;
  is_tagged: boolean;
  path: string;
}

export interface CameraConfig {
  archived: Timestamp | null;
  boot_time_delay: number;
  camera_id: number;
  check_in_time: string | null;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  pan: number | null;
  selected_preset: number;
  tilt: number | null;
  zoom: number | null;
}

export interface CameraConfigPreset {
  archived: Timestamp | null;
  camera_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  local_preset_id: number;
  pan: number;
  tilt: number;
  zoom: number;
}

export interface CameraConfigRotation {
  archived: Timestamp | null;
  camera_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  rotation: number;
}

export interface CameraDataRecord {
  camera_id: number;
  date: Timestamp;
  id: Generated<Int8>;
}

export interface CameraDetectionData {
  camera_data_record_id: Int8;
  confidence: number;
  id: Generated<number>;
  object: string;
  present_duration: number;
  stalled: boolean;
  water_level: number;
}

export interface Channel {
  archived: Timestamp | null;
  channel_type_id: number;
  device_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  local_id: number;
}

export interface ChannelConfig {
  active: boolean;
  archived: Timestamp | null;
  category: string;
  channel_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  name: string;
  offset: number;
  scale: number;
  units: string;
}

export interface ChannelConfigAccumulation {
  archived: Timestamp | null;
  channel_id: number;
  drain_const: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  source_local_id: number;
}

export interface ChannelConfigDisplay {
  archived: Timestamp | null;
  channel_id: number;
  display_index: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
}

export interface ChannelConfigInternalPowerSensor {
  archived: Timestamp | null;
  channel_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  measurement_type: InternalPowerSensorMeasurementType;
}

export interface ChannelConfigSdi12 {
  address: string;
  archived: Timestamp | null;
  channel_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  measurement_index: number;
  measurement_set: number;
}

export interface ChannelConfigTilt {
  alignment_x: number | null;
  alignment_y: number | null;
  alignment_z: number | null;
  archived: Timestamp | null;
  channel_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
}

export interface ChannelError {
  archived: Timestamp | null;
  channel_id: number;
  error_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
}

export interface City {
  id: Generated<number>;
  name: string;
  state: string;
}

export interface Client {
  deleted_at: Timestamp | null;
  id: Generated<number>;
  name: string;
}

export interface ClientGaugeStation {
  client_id: number;
  gauge_station_id: number;
  id: Generated<number>;
}

export interface ControlAuditLog {
  actor_user_id: string;
  date: Timestamp;
  device_id: number;
  id: Generated<number>;
  log_action_id: number;
}

export interface Device {
  archived: Timestamp | null;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  serial_number: string;
}

export interface DeviceCameraAccumulationTrigger {
  accumulation_time: number;
  archived: Timestamp | null;
  camera_id: number;
  device_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  trigger_amount: number;
}

export interface DeviceCameraAccumulationTriggerActive {
  active: boolean;
  archived: Timestamp | null;
  camera_id: number;
  device_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
}

export interface DeviceCameraTrigger {
  archived: Timestamp | null;
  device_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  source_id: number | null;
  triggered: boolean;
}

export interface DeviceCameraTriggerOverride {
  archived: Timestamp | null;
  device_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  source_id: number | null;
  trigger_override: boolean | null;
}

export interface DeviceConnected {
  archived: Timestamp | null;
  connected: boolean;
  device_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
}

export interface DeviceConnectionQuality {
  archived: Timestamp | null;
  device_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  max_rsrp: number | null;
  max_rsrq: number | null;
  max_rssi: number | null;
  min_rsrp: number | null;
  min_rsrq: number | null;
  min_rssi: number | null;
}

export interface DeviceDatalogging {
  archived: Timestamp | null;
  device_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  timestep: number;
}

export interface DeviceInfo {
  activation_date: Timestamp | null;
  active: boolean | null;
  archived: Timestamp | null;
  device_id: number;
  gauge_station_id: number | null;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  latitude: number | null;
  longitude: number | null;
  page_version: string | null;
  type: DeviceType;
  warranty_end_date: Timestamp | null;
}

export interface DeviceNetworking {
  api_version: string;
  archived: Timestamp | null;
  device_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  protocol: ProtocolType;
}

export interface DevicePower {
  archived: Timestamp | null;
  device_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  max_voltage: number;
  min_voltage: number;
}

export interface DeviceSim {
  archived: Timestamp | null;
  device_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  sim_id: number;
  sim_index: number | null;
}

export interface DeviceSimActive {
  active_sim_index: number;
  archived: Timestamp | null;
  device_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
}

export interface DeviceWifiInterfaceActive {
  archived: Timestamp | null;
  device_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  wifi_active: boolean;
}

export interface DeviceWifiInterfaceConfig {
  archived: Timestamp | null;
  device_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  password: Buffer;
  salt: Generated<string>;
}

export interface GaugeStation {
  archived: Timestamp | null;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  name: string;
}

export interface GaugeStationInfo {
  active: Generated<boolean>;
  archived: Timestamp | null;
  city_id: number;
  gauge_station_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  latitude: number;
  location: string;
  longitude: number;
  publicly_visible: Generated<boolean>;
}

export interface GrantedPermission {
  id: Generated<number>;
  permission_id: number;
  user_id: string;
}

export interface IncidentCategory {
  category: string;
  id: Generated<number>;
}

export interface IncidentType {
  id: Generated<number>;
  incident_category_id: number;
  type: string;
}

export interface Invite {
  client_id: number | null;
  expires_at: Timestamp | null;
  id: Generated<number>;
  role_id: number | null;
  sender_user_id: string;
  token: string | null;
}

export interface MeasurementCategory {
  archived: Timestamp | null;
  category: string;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
}

export interface MeasurementRecord {
  channel_id: number;
  date: Timestamp;
  id: Generated<Int8>;
  value: number | null;
}

export interface MeasurementRecordLatest {
  channel_id: number;
  date: Timestamp;
  id: Generated<Int8>;
  value: number | null;
}

export interface Permission {
  assign_role: boolean;
  description: string;
  id: Generated<number>;
  name: string;
}

export interface Preference {
  data_vis_preset: Json | null;
  favorite: Json | null;
  id: Generated<number>;
  layers_on_load: Json | null;
  map_style: string | null;
  theme: string | null;
  user_id: string;
}

export interface RiskLevelMonitor {
  archived: Timestamp | null;
  device_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  local_id: number;
  type_id: number;
}

export interface RiskLevelMonitorChannel {
  archived: Timestamp | null;
  channel_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  risk_level_monitor_id: number;
}

export interface RiskLevelMonitorConfig {
  archived: Timestamp | null;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  priority: number;
  risk_level_monitor_id: number;
}

export interface RiskLevelMonitorConfigGradient {
  archived: Timestamp | null;
  begin_risk_level: number;
  begin_value: number;
  end_risk_level: number;
  end_value: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  risk_level_monitor_id: number;
}

export interface RiskLevelMonitorConfigOverride {
  archived: Timestamp | null;
  device_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  risk_level: number;
}

export interface RiskLevelMonitorConfigRange {
  archived: Timestamp | null;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  max_value: number;
  min_value: number;
  risk_level: number;
  risk_level_monitor_id: number;
}

export interface Role {
  client_id: number;
  deleted_at: Timestamp | null;
  id: Generated<number>;
  name: string;
}

export interface RolePermission {
  id: Generated<number>;
  permission_id: number;
  role_id: number;
}

export interface RolePermissionsAuditLog {
  actor_user_id: string;
  added: boolean;
  date: Timestamp;
  id: Generated<number>;
  log_action_id: number;
  permission_id: number | null;
  role_name: string;
}

export interface SeasonalReport {
  date: Timestamp;
  device_id: number;
  id: Generated<number>;
  note: string;
  passed: boolean;
  seasonal_report_type_id: number;
  user_id: string;
}

export interface SeasonalReportAnswer {
  id: Generated<number>;
  response: SeasonalReportQuestionResponse;
  seasonal_report_id: number;
  seasonal_report_question_id: number;
}

export interface SeasonalReportImage {
  description: string;
  id: Generated<number>;
  path: string;
  seasonal_report_id: number;
}

export interface SeasonalReportQuestion {
  expected_response: SeasonalReportQuestionResponse;
  id: Generated<number>;
  is_critical: boolean;
  question_text: string;
  seasonal_report_question_category_id: number;
}

export interface SeasonalReportQuestionCategory {
  category: string;
  id: Generated<number>;
}

export interface SeasonalReportType {
  id: Generated<number>;
  report_type: string;
}

export interface SeasonalReportTypeQuestion {
  id: Generated<number>;
  seasonal_report_question_id: number;
  seasonal_report_type_id: number;
}

export interface Session {
  created_at: Timestamp;
  expires_at: Timestamp;
  id: string;
  ip_address: string | null;
  token: string;
  updated_at: Timestamp;
  user_agent: string | null;
  user_id: string;
}

export interface Sim {
  archived: Timestamp | null;
  iccid: string;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  provider: string;
}

export interface SimInfo {
  activated: boolean;
  archived: Timestamp | null;
  id: Generated<number>;
  imei: string | null;
  introduced: Generated<Timestamp>;
  paused: Generated<boolean>;
  sim_id: number;
}

export interface SimInfoEmnify {
  archived: Timestamp | null;
  bic: string;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  sim_id: number;
}

export interface SimInfoHologram {
  archived: Timestamp | null;
  device_id: number | null;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  sim_id: number;
}

export interface TimestepModifier {
  archived: Timestamp | null;
  device_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  local_id: number;
  type_id: number;
}

export interface TimestepModifierChannel {
  archived: Timestamp | null;
  channel_id: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  timestep_modifier_id: number;
}

export interface TimestepModifierConfig {
  archived: Timestamp | null;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  min_timestep: number;
  priority: number;
  timestep_modifier_id: number;
}

export interface TimestepModifierConfigDeltaValue {
  archived: Timestamp | null;
  delta_value: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  min_change: number;
  timestep_modifier_id: number;
}

export interface TimestepModifierConfigEnabled {
  archived: Timestamp | null;
  enabled: boolean;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  timestep_modifier_id: number;
}

export interface TimestepModifierConfigGradient {
  archived: Timestamp | null;
  begin_value: number;
  end_value: number;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  timestep_modifier_id: number;
}

export interface TimestepModifierConfigRange {
  archived: Timestamp | null;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
  max_value: number;
  min_value: number;
  timestep_modifier_id: number;
}

export interface UniversalMeasurementCategory {
  archived: Timestamp | null;
  category: string;
  id: Generated<number>;
  introduced: Generated<Timestamp>;
}

export interface User {
  client_id: number;
  created_at: Timestamp;
  deleted_at: Timestamp | null;
  email: string;
  email_verified: boolean;
  id: string;
  image: string | null;
  name: string;
  phone_number: Buffer | null;
  phone_number_verified: boolean;
  role_id: number | null;
  salt: Generated<string>;
  updated_at: Timestamp;
}

export interface UserAuditLog {
  actor_user_id: string;
  date: Timestamp;
  id: Generated<number>;
  log_action_id: number;
  target_user_id: string;
}

export interface Verification {
  created_at: Timestamp;
  expires_at: Timestamp;
  id: string;
  identifier: string;
  updated_at: Timestamp;
  value: string;
}

export interface VmqAuthAcl {
  client_id: string;
  device_id: number | null;
  id: Generated<number>;
  mountpoint: string;
  password: string | null;
  publish_acl: Json | null;
  subscribe_acl: Json | null;
  username: string;
}

export interface WorkOrder {
  created_at: Timestamp;
  creator_user_id: string;
  device_id: number;
  id: Generated<number>;
  incident_type_id: number;
  priority: number;
  state: WorkOrderState;
  work_order_status_id: number;
}

export interface WorkOrderStatus {
  id: Generated<number>;
  status: string;
}

export interface WorkOrderUpdate {
  created_at: Timestamp;
  description: string;
  id: Generated<number>;
  new_priority: number;
  new_state: WorkOrderState;
  new_work_order_status_id: number;
  user_id: string;
  work_order_id: number;
}

export interface WorkOrderUpdateImage {
  description: string;
  id: Generated<number>;
  path: string;
  work_order_id: number;
}

export interface DB {
  accepted_invites: AcceptedInvites;
  account: Account;
  alert: Alert;
  alert_info: AlertInfo;
  alert_monitor: AlertMonitor;
  alert_monitor_channel: AlertMonitorChannel;
  alert_monitor_config: AlertMonitorConfig;
  alert_monitor_config_activity: AlertMonitorConfigActivity;
  alert_monitor_config_activity_override: AlertMonitorConfigActivityOverride;
  alert_monitor_config_enabled: AlertMonitorConfigEnabled;
  alert_monitor_config_range: AlertMonitorConfigRange;
  alert_subscription: AlertSubscription;
  asset: Asset;
  asset_type: AssetType;
  audit_log_action: AuditLogAction;
  camera: Camera;
  camera_capture_data: CameraCaptureData;
  camera_config: CameraConfig;
  camera_config_preset: CameraConfigPreset;
  camera_config_rotation: CameraConfigRotation;
  camera_data_record: CameraDataRecord;
  camera_detection_data: CameraDetectionData;
  channel: Channel;
  channel_config: ChannelConfig;
  channel_config_accumulation: ChannelConfigAccumulation;
  channel_config_display: ChannelConfigDisplay;
  channel_config_internal_power_sensor: ChannelConfigInternalPowerSensor;
  channel_config_sdi12: ChannelConfigSdi12;
  channel_config_tilt: ChannelConfigTilt;
  channel_error: ChannelError;
  city: City;
  client: Client;
  client_gauge_station: ClientGaugeStation;
  control_audit_log: ControlAuditLog;
  device: Device;
  device_camera_accumulation_trigger: DeviceCameraAccumulationTrigger;
  device_camera_accumulation_trigger_active: DeviceCameraAccumulationTriggerActive;
  device_camera_trigger: DeviceCameraTrigger;
  device_camera_trigger_override: DeviceCameraTriggerOverride;
  device_connected: DeviceConnected;
  device_connection_quality: DeviceConnectionQuality;
  device_datalogging: DeviceDatalogging;
  device_info: DeviceInfo;
  device_networking: DeviceNetworking;
  device_power: DevicePower;
  device_sim: DeviceSim;
  device_sim_active: DeviceSimActive;
  device_wifi_interface_active: DeviceWifiInterfaceActive;
  device_wifi_interface_config: DeviceWifiInterfaceConfig;
  gauge_station: GaugeStation;
  gauge_station_info: GaugeStationInfo;
  granted_permission: GrantedPermission;
  incident_category: IncidentCategory;
  incident_type: IncidentType;
  invite: Invite;
  measurement_category: MeasurementCategory;
  measurement_record: MeasurementRecord;
  measurement_record_latest: MeasurementRecordLatest;
  permission: Permission;
  preference: Preference;
  risk_level_monitor: RiskLevelMonitor;
  risk_level_monitor_channel: RiskLevelMonitorChannel;
  risk_level_monitor_config: RiskLevelMonitorConfig;
  risk_level_monitor_config_gradient: RiskLevelMonitorConfigGradient;
  risk_level_monitor_config_override: RiskLevelMonitorConfigOverride;
  risk_level_monitor_config_range: RiskLevelMonitorConfigRange;
  role: Role;
  role_permission: RolePermission;
  role_permissions_audit_log: RolePermissionsAuditLog;
  seasonal_report: SeasonalReport;
  seasonal_report_answer: SeasonalReportAnswer;
  seasonal_report_image: SeasonalReportImage;
  seasonal_report_question: SeasonalReportQuestion;
  seasonal_report_question_category: SeasonalReportQuestionCategory;
  seasonal_report_type: SeasonalReportType;
  seasonal_report_type_question: SeasonalReportTypeQuestion;
  session: Session;
  sim: Sim;
  sim_info: SimInfo;
  sim_info_emnify: SimInfoEmnify;
  sim_info_hologram: SimInfoHologram;
  timestep_modifier: TimestepModifier;
  timestep_modifier_channel: TimestepModifierChannel;
  timestep_modifier_config: TimestepModifierConfig;
  timestep_modifier_config_delta_value: TimestepModifierConfigDeltaValue;
  timestep_modifier_config_enabled: TimestepModifierConfigEnabled;
  timestep_modifier_config_gradient: TimestepModifierConfigGradient;
  timestep_modifier_config_range: TimestepModifierConfigRange;
  universal_measurement_category: UniversalMeasurementCategory;
  user: User;
  user_audit_log: UserAuditLog;
  verification: Verification;
  vmq_auth_acl: VmqAuthAcl;
  work_order: WorkOrder;
  work_order_status: WorkOrderStatus;
  work_order_update: WorkOrderUpdate;
  work_order_update_image: WorkOrderUpdateImage;
}
