/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AcceptedInvites {
  /**
   * When the invite was accepted
   */
  accepted_date: Generated<Timestamp>;
  /**
   * Unique identifier for the acceptance record
   */
  id: Generated<number>;
  /**
   * The invite that was accepted. Reusable invite tokens may have many acceptance rows
   */
  invite_id: number;
  /**
   * The user created by accepting the invite
   */
  user_id: string;
}

export interface Account {
  /**
   * The access token of the account. Returned by the provider
   */
  access_token: string | null;
  /**
   * When the access token expires
   */
  access_token_expires_at: Timestamp | null;
  /**
   * The ID of the account as provided by the SSO, or equal to user_id for credential accounts
   */
  account_id: string;
  /**
   * When the account was created
   */
  created_at: Generated<Timestamp>;
  /**
   * Unique identifier for each account
   */
  id: string;
  /**
   * The ID token returned from the provider
   */
  id_token: string | null;
  /**
   * The password of the account. Mainly used for email and password authentication
   */
  password: string | null;
  /**
   * The ID of the provider
   */
  provider_id: string;
  /**
   * The refresh token of the account. Returned by the provider
   */
  refresh_token: string | null;
  /**
   * When the refresh token expires
   */
  refresh_token_expires_at: Timestamp | null;
  /**
   * The scope of the account. Returned by the provider
   */
  scope: string | null;
  /**
   * When the account was updated
   */
  updated_at: Timestamp;
  /**
   * The ID of the user
   */
  user_id: string;
}

export interface AuditLogAction {
  /**
   * Stable machine key
   */
  action_id: string;
  /**
   * Human-readable label
   */
  action_text: string;
  id: Generated<number>;
}

export interface Client {
  /**
   * Unique identifier for each client
   */
  id: Generated<number>;
  /**
   * Name of the client
   */
  name: string;
}

export interface ControlAuditLog {
  /**
   * The user who performed the action
   */
  actor_id: string;
  /**
   * When the action occurred
   */
  date: Generated<Timestamp>;
  /**
   * The device acted upon
   */
  device_id: number;
  id: Generated<number>;
  /**
   * What action was performed
   */
  log_action_id: number;
}

export interface Device {
  /**
   * Placeholder device identifier
   */
  id: Generated<number>;
}

export interface GrantedPermission {
  id: Generated<number>;
  permission_id: number;
  user_id: string;
}

export interface Invite {
  /**
   * The client the invitee will belong to
   */
  client_id: number;
  /**
   * When the invite token expires. NULL means the invite is a permalink
   */
  expires_at: Timestamp | null;
  /**
   * Unique identifier for invites
   */
  id: Generated<number>;
  /**
   * The role the invited user will receive on signup
   */
  role_id: number;
  /**
   * The user who sent the invite
   */
  sender_user_id: string;
  /**
   * varchar(32) for the invite token url
   */
  token: string;
}

export interface Permission {
  /**
   * Whether this permission may be attached to a role. false means it can only be granted to an individual user
   */
  assign_role: boolean;
  /**
   * Description of what the permission does
   */
  description: string;
  /**
   * Unique identifier for a permission
   */
  id: Generated<number>;
  /**
   * Name of the permission
   */
  name: string;
}

export interface Preference {
  /**
   * User presets for data visualizer graph
   */
  data_vis_preset: Json | null;
  /**
   * (mobile) The favorites the user wants at the top of the bottom drawer menu
   */
  favorite: Json | null;
  /**
   * Unique identifier for each preference row
   */
  id: Generated<number>;
  /**
   * The layers the user wants to see on the map on load
   */
  layers_on_load: Json | null;
  /**
   * The style of map the user chooses to display on render
   */
  map_style: string | null;
  /**
   * The theme of the app the user wants on load
   */
  theme: string | null;
  /**
   * The ID of the user. One preference row per user
   */
  user_id: string;
}

export interface Role {
  /**
   * The client this role belongs to. Nullable — see open items
   */
  client_id: number | null;
  /**
   * Unique identifier for each role
   */
  id: Generated<number>;
  /**
   * Name of the role (clients may choose their own names)
   */
  name: string;
}

export interface RolePermission {
  id: Generated<number>;
  permission_id: number;
  role_id: number;
}

export interface RolesPermsAuditLog {
  /**
   * The user who performed the action
   */
  actor_id: string;
  /**
   * TRUE if the permission was added, FALSE if removed
   */
  added: boolean | null;
  /**
   * When the action occurred
   */
  date: Generated<Timestamp>;
  id: Generated<number>;
  /**
   * What action was performed
   */
  log_action_id: number;
  /**
   * The permission affected
   */
  permission_id: number | null;
  /**
   * The role affected
   */
  role_id: number | null;
}

export interface Session {
  /**
   * When the session was created
   */
  created_at: Generated<Timestamp>;
  /**
   * When the session expires
   */
  expires_at: Timestamp;
  /**
   * Unique identifier for each session
   */
  id: string;
  /**
   * The IP address of the device
   */
  ip_address: string | null;
  /**
   * The unique session token
   */
  token: string;
  /**
   * When the session was updated
   */
  updated_at: Timestamp;
  /**
   * The user agent information of the device
   */
  user_agent: string | null;
  /**
   * The ID of the user
   */
  user_id: string;
}

export interface User {
  /**
   * The client this user belongs to
   */
  client_id: number;
  /**
   * When the user account was created
   */
  created_at: Generated<Timestamp>;
  /**
   * UTC timestamp this user record was deleted. NULL means active/current
   */
  deleted_at: Timestamp | null;
  /**
   * User's email address for communication and login
   */
  email: string;
  /**
   * Whether the user's email is verified
   */
  email_verified: boolean;
  /**
   * Unique identifier for each user
   */
  id: string;
  /**
   * User's image url
   */
  image: string | null;
  /**
   * User's chosen display name
   */
  name: string;
  /**
   * Armored pgcrypto ciphertext for the user's phone number
   */
  phone_number: string | null;
  /**
   * Whether the user's phone number is verified
   */
  phone_number_verified: Generated<boolean>;
  /**
   * The user's single role
   */
  role_id: number;
  /**
   * Salt used with the encryption key for encrypted user fields
   */
  salt: Generated<string>;
  /**
   * Last update to the user's information
   */
  updated_at: Timestamp;
}

export interface UserAuditLog {
  /**
   * The user who performed the action
   */
  actor_id: string;
  /**
   * When the action occurred
   */
  date: Generated<Timestamp>;
  id: Generated<number>;
  /**
   * What action was performed
   */
  log_action_id: number;
  /**
   * The user the action was performed on
   */
  target_id: string;
}

export interface Verification {
  /**
   * When the verification request was created
   */
  created_at: Generated<Timestamp>;
  /**
   * When the verification request expires
   */
  expires_at: Timestamp;
  /**
   * Unique identifier for each verification
   */
  id: string;
  /**
   * The identifier for the verification request
   */
  identifier: string;
  /**
   * When the verification request was updated
   */
  updated_at: Timestamp;
  /**
   * The value to be verified
   */
  value: string;
}

export interface DB {
  accepted_invites: AcceptedInvites;
  account: Account;
  audit_log_action: AuditLogAction;
  client: Client;
  control_audit_log: ControlAuditLog;
  device: Device;
  granted_permission: GrantedPermission;
  invite: Invite;
  permission: Permission;
  preference: Preference;
  role: Role;
  role_permission: RolePermission;
  roles_perms_audit_log: RolesPermsAuditLog;
  session: Session;
  user: User;
  user_audit_log: UserAuditLog;
  verification: Verification;
}
